config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index1'
  root "home#index1"

  resources :brands,param: :alias_name do
    member do
      #get ""
    end
  end
  get ':alias_name/:phone_alias_name' => "phones#show"
  get ':alias_name' => "brands#show"
  resources :phone_details
  resources :phones,param: :alias_name
  resources :articles,path: 'blog'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone.rb
class Phone < ApplicationRecord
	has_many :phone_details
	belongs_to :brand
	has_attached_file :image, styles: { medium: "160x212>", thumb: "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	after_create :add_phone_details
	def to_param
  		alias_name
	end

	def add_phone_details
		self.phone_details.build().save
	end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all.order("brand_id ASC")
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    # if params[:alias_name] == "blog"
    #   @post = Article.new
    #   render :template => "articles/new"
    # else
    #   @phone_detail = @phone.phone_details.first
    # end
    @phone_detail = @phone.phone_details.first
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)
    @phone.alias_name = @phone.name
    respond_to do |format|
      if @phone.save
        format.html { redirect_to phone_path(alias_name: @phone.alias_name.gsub(" ","_")), notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    params[:phone][:alias_name] = params[:phone][:name]
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to phone_path(alias_name: @phone.alias_name.gsub(" ","_")), notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      if params[:phone_alias_name].present?
        @phone = Phone.find_by(alias_name:  params[:phone_alias_name].gsub("_"," "))
      else
        @phone = Phone.find_by(alias_name:  params[:alias_name].gsub("_"," "))
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.fetch(:phone).permit(:name,:image,:alias_name,:brand_id,:release_date)
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= simple_form_for(phone) do |f| %>
  <% if phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :name,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%#= f.input :brand_id, as: :select, class: "chosen-select", collection: Brand.all, value_method: :id,inclide_blank: false,input_html: {class: "form-control"}  %>
    <%= f.label "Brand" %><br/>
    <%= f.collection_select :brand_id,Brand.all,:id,:name,{},class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :release_date ,as: :datetime%>
  </div>
  <div class="form-group">
    <%= f.input :image,as: :file,input_html: {class: "form-control"} %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %><br/>

app/views/phones/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing Phone</h1>

		<%= render 'form', phone: @phone %>

		<%= link_to 'Show', @phone %> |
		<%= link_to 'Back', phones_path %>
	</div>
</div>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="clearfix col-md-10 text-left"><h1>Phones</h1></div>
  <div class="col-md-2 text-right" style="margin-top:30px;"><%= link_to 'Add New Phone', new_phone_path ,class: "btn btn-primary"%></div>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th> Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.name %></td>
        <td><%= phone.brand.name %></td>
        <td><%= phone.image.present? ? image_tag(phone.image.url(:thumb)) : "N/A" rescue "N/A" %></td>
        <td><%= link_to 'Show',phone_path(phone_alias_name: phone.alias_name.gsub(" ","_"))  %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone.alias_name.gsub(" ","_")) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Add New Phone', new_phone_path ,class: "btn btn-primary"%>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', phones_path %>

app/views/phones/show1.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @phone_detail.phone.name + " Details" %></h1>

<table>
  <tr>
    <th>Name: &nbsp;</th>
    <td><%= @phone_detail.phone.name %></td>
  </tr>
  <tr>
    <th>Size: &nbsp;</th>
    <td><%= @phone_detail.display_size rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Resolution: &nbsp;</th>
    <td><%= @phone_detail.display_resolution rescue "N/A"%></td>
  </tr>
  <tr></tr>
  <tr>
    <th>Display Type: &nbsp;</th>
    <td><%= @phone_detail.display_type rescue "N/A"%></td>
  </tr>

  <tr>
    <th>Multitouch: &nbsp;</th>
    <td><%= @phone_detail.display_multitouch rescue "N/A"%></td>
  </tr>
  <tr>
    <th>RAM: &nbsp;</th>
    <td><%= @phone_detail.ram rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Chipset: &nbsp;</th>
    <td><%= @phone_detail.chipset rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Capacity: &nbsp;</th>
    <td><%= @phone_detail.battery_capacity rescue "N/A"%></td>
  </tr>

  <tr>
    <th>Battery Technology: &nbsp;</th>
    <td><%= @phone_detail.battery_technology rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Technology: &nbsp;</th>
    <td><%= @phone_detail.technology rescue "N/A"%></td>
  </tr>
  <tr>
    <th>2G: &nbsp;</th>
    <td><%= @phone_detail["2g_bands"] rescue "N/A"%></td>
  </tr>
  <tr>
    <th>3G: &nbsp;</th>
    <td><%= @phone_detail["3g_bands"] rescue "N/A"%></td>
  </tr>

  <tr>
    <th>4G: &nbsp;</th>
    <td><%= @phone_detail["4g_bands"] rescue "N/A"%></td>
  </tr>
  <tr>
    <th>GPRS: &nbsp;</th>
    <td><%= @phone_detail.gprs rescue "N/A"%></td>
  </tr>
  <tr>
    <th>EDGE: &nbsp;</th>
    <td><%= @phone_detail.edge rescue "N/A" %></td>
  </tr>
  <tr>
    <th>Announced: &nbsp;</th>
    <td><%= @phone_detail.announced rescue "N/A" %></td>
  </tr>
</table>
    
<%= link_to 'Edit', edit_phone_detail_path(@phone_detail) %> |
<%= link_to 'Back', phone_details_path %><br><br><br><br>