config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index1'
  root "home#index1"

  resources :brands,param: :alias_name do
    member do
      #get ""
    end
  end
  get ':alias_name/:phone_alias_name' => "phones#show"
  get ':alias_name' => "brands#show"
  resources :phone_details
  resources :phones,param: :alias_name
  resources :articles,path: 'blog'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone_detail.rb
class PhoneDetail < ApplicationRecord
	belongs_to :phone
	belongs_to :brand
end

app/controllers/phone_details_controller.rb
class PhoneDetailsController < ApplicationController
  before_action :set_phone_detail, only: [:show, :edit, :update, :destroy]

  # GET /phone_details
  # GET /phone_details.json
  def index
    @phone_details = PhoneDetail.all.order("brand_id ASC")
  end

  # GET /phone_details/1
  # GET /phone_details/1.json
  def show
  end

  # GET /phone_details/new
  def new
    @phone_detail = PhoneDetail.new
  end

  # GET /phone_details/1/edit
  def edit
  end

  # POST /phone_details
  # POST /phone_details.json
  def create
    @phone_detail = PhoneDetail.new(phone_detail_params)

    respond_to do |format|
      if @phone_detail.save
        format.html { redirect_to @phone_detail, notice: 'Phone detail was successfully created.' }
        format.json { render :show, status: :created, location: @phone_detail }
      else
        format.html { render :new }
        format.json { render json: @phone_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_details/1
  # PATCH/PUT /phone_details/1.json
  def update
    respond_to do |format|
      if @phone_detail.update(phone_detail_params)
        format.html { redirect_to @phone_detail, notice: 'Phone detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_detail }
      else
        format.html { render :edit }
        format.json { render json: @phone_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_details/1
  # DELETE /phone_details/1.json
  def destroy
    @phone_detail.destroy
    respond_to do |format|
      format.html { redirect_to phone_details_url, notice: 'Phone detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_detail
      @phone_detail = PhoneDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_detail_params
      params.fetch(:phone_detail).permit(:phone_id,:display_size,:display_resolution,:display_type,:display_multitouch,
        :ram,:chipset,:battery_capacity,:battery_technology,:technology,"2g_bands","3g_bands","4g_bands",:gprs,:edge,
        :announced,:status,:dimensions,:weight,:sim,:os,:cpu,:gpu,:card_slot,:internal_memory,:primary_camera,:camera_features,
        :video,:secondary_camera,:alert_types,:loud_speaker,"3.5mm_jack",:wlan,:bluetooth,:gps,:nfc,:sensors,:messaging,:browser,:java,
        :colors,:price_group,:image)
    end
end

app/helpers/phone_details_helper.rb
module PhoneDetailsHelper
end

app/views/phone_details/_form.html.erb
<%= simple_form_for(phone_detail) do |f| %>
  <% if phone_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_detail.errors.count, "error") %> prohibited this phone_detail from being saved:</h2>

      <ul>
      <% phone_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :display_size,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :display_resolution,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :display_type,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :display_multitouch,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :ram,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :chipset,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :battery_capacity,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :battery_technology,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :battery_type,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :technology,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input "2g_bands",input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input "3g_bands",input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input "4g_bands",input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :gprs,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :edge,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :announced,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :status,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :dimensions,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :weight,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :sim,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :os,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :cpu,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :gpu,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :card_slot,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :internal_memory,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :primary_camera,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :camera_features,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :video,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :secondary_camera,input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :alert_types,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :loud_speaker,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input "3.5mm_jack",input_html: {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.input :wlan,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :bluetooth,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :gps,input_html: {class: "form-control"} %>
  </div>



  <div class="form-group">
    <%= f.input :nfc,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :sensors,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :messaging,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :browser,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :java,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :colors,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :price_in_rupees,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :price_in_dollar,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :protection,input_html: {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :speed,input_html: {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_details/edit.html.erb
<h1>Editing Phone Detail</h1>

<%= render 'form', phone_detail: @phone_detail %>

<%= link_to 'Show', @phone_detail %> |
<%= link_to 'Back', phone_details_path %>

app/views/phone_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Details</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Phone</th>
      <th>Brand</th>
      <th>RAM</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_details.each do |phone_detail| %>
      <tr>
        <td><%= phone_detail.phone.name %></td>
        <td><%= phone_detail.phone.brand.name %></td>
        <td><%= phone_detail.ram || "N/A" %></td>
        <td><%= link_to 'Show', phone_detail %></td>
        <td><%= link_to 'Edit', edit_phone_detail_path(phone_detail) %></td>
        <td><%= link_to 'Destroy', phone_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Detail', new_phone_detail_path %>

app/views/phone_details/new.html.erb
<h1>New Phone Detail</h1>

<%= render 'form', phone_detail: @phone_detail %>

<%= link_to 'Back', phone_details_path %>

app/views/phone_details/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @phone_detail.phone.name + " Details" %></h1>

<table>
	<tr>
		<th>Name: &nbsp;</th>
		<td><%= @phone_detail.phone.name %></td>
	</tr>
	<tr>
		<th>Size: &nbsp;</th>
		<td><%= @phone_detail.display_size rescue "N/A"%></td>
	</tr>
	<tr>
		<th>Resolution: &nbsp;</th>
		<td><%= @phone_detail.display_resolution rescue "N/A"%></td>
	</tr>
	<tr></tr>
	<tr>
		<th>Display Type: &nbsp;</th>
		<td><%= @phone_detail.display_type rescue "N/A"%></td>
	</tr>

	<tr>
		<th>Multitouch: &nbsp;</th>
		<td><%= @phone_detail.display_multitouch rescue "N/A"%></td>
	</tr>
	<tr>
		<th>RAM: &nbsp;</th>
		<td><%= @phone_detail.ram rescue "N/A"%></td>
	</tr>
	<tr>
		<th>Chipset: &nbsp;</th>
		<td><%= @phone_detail.chipset rescue "N/A"%></td>
	</tr>
	<tr>
		<th>Capacity: &nbsp;</th>
		<td><%= @phone_detail.battery_capacity rescue "N/A"%></td>
	</tr>

	<tr>
		<th>Battery Technology: &nbsp;</th>
		<td><%= @phone_detail.battery_technology rescue "N/A"%></td>
	</tr>
	<tr>
		<th>Technology: &nbsp;</th>
		<td><%= @phone_detail.technology rescue "N/A"%></td>
	</tr>
	<tr>
		<th>2G: &nbsp;</th>
		<td><%= @phone_detail["2g_bands"] rescue "N/A"%></td>
	</tr>
	<tr>
		<th>3G: &nbsp;</th>
		<td><%= @phone_detail["3g_bands"] rescue "N/A"%></td>
	</tr>

	<tr>
		<th>4G: &nbsp;</th>
		<td><%= @phone_detail["4g_bands"] rescue "N/A"%></td>
	</tr>
	<tr>
		<th>GPRS: &nbsp;</th>
		<td><%= @phone_detail.gprs rescue "N/A"%></td>
	</tr>
	<tr>
		<th>EDGE: &nbsp;</th>
		<td><%= @phone_detail.edge rescue "N/A" %></td>
	</tr>
	<tr>
		<th>Announced: &nbsp;</th>
		<td><%= @phone_detail.announced rescue "N/A" %></td>
	</tr>
</table>
		
<%= link_to 'Edit', edit_phone_detail_path(@phone_detail) %> |
<%= link_to 'Back', phone_details_path %><br><br><br><br>

<!-- Code by Dixit -->
<h3>TECH SPEC</h3>
<div class="row spec-list">
	<div class="col-md-3">
		<h4>Processor</h4>
	</div>
	<div class="col-md-9">
		<ul>
			<li>
				<div class="spec">
					<h5 class="spec-title">Memory</h5>
					<div class="spec-desc">
						<p>
							2GB RAM
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Speed</h5>
					<div class="spec-desc">
						<p>
							1.6GHz
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Type</h5>
					<div class="spec-desc">
						<p>
							Octa-core
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="row spec-list">
	<div class="col-md-3">
		<h4>Processor</h4>
	</div>
	<div class="col-md-9">
		<ul>
			<li>
				<div class="spec">
					<h5 class="spec-title">Memory</h5>
					<div class="spec-desc">
						<p>
							2GB RAM
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Speed</h5>
					<div class="spec-desc">
						<p>
							1.6GHz
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Type</h5>
					<div class="spec-desc">
						<p>
							Octa-core
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="row spec-list">
	<div class="col-md-3">
		<h4>Processor</h4>
	</div>
	<div class="col-md-9">
		<ul>
			<li>
				<div class="spec">
					<h5 class="spec-title">Memory</h5>
					<div class="spec-desc">
						<p>
							2GB RAM
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Speed</h5>
					<div class="spec-desc">
						<p>
							1.6GHz
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">CPU Type</h5>
					<div class="spec-desc">
						<p>
							Octa-core
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="spec">
					<h5 class="spec-title">Resolution</h5>
					<div class="spec-desc">
						<p>
							1080 x 1920 (FHD)
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>