config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index1'
  root "home#index1"

  resources :brands,param: :alias_name do
    member do
      #get ""
    end
  end
  get ':alias_name/:phone_alias_name' => "phones#show"
  get ':alias_name' => "brands#show"
  resources :phone_details
  resources :phones,param: :alias_name
  resources :articles,path: 'blog'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,:body, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
  # Index action to render all posts
  def index
    @posts = Article.all
  end

  # New action for creating post
  def new
    @post = Article.new
  end

  # Create action saves the post into database
  def create
    @post = Article.new(article_params)
    if @post.save
      flash[:notice] = "Successfully created article!"
      redirect_to article_path(@post)
    else
      flash[:alert] = "Error creating new article!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    @post = Article.find(params[:id])
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(article_params)
      flash[:notice] = "Successfully updated article!"
      redirect_to article_path(@post)
    else
      flash[:alert] = "Error updating article!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @post = Article.find(params[:id])
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def article_params
    params.fetch(:article).permit(:title, :body)
  end

  def find_post
    @post = Article.find(params[:id])
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit the post</h1>
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<%= link_to 'Create New Post',new_article_path %>

app/views/articles/new.html.erb
<h2>Create New Post</h2>

<%= render "articles/form" %>

app/views/articles/show.html.erb
<h1>Title</h1>
<%= @post.title %>
<h1>Body</h1>
<p><%= raw(@post.body) %></p>