config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index1'
  root "home#index1"

  resources :brands,param: :alias_name do
    member do
      #get ""
    end
  end
  get ':alias_name/:phone_alias_name' => "phones#show"
  get ':alias_name' => "brands#show"
  resources :phone_details
  resources :phones,param: :alias_name
  resources :articles,path: 'blog'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :phones
	has_many :phone_details
	has_attached_file :image, styles: { large: "500x500>", medium: "420x420>", thumb: "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	has_attached_file :logo, styles: { thumb: "100x100>" }
	validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	def to_param
  	 alias_name
	end
	
	def Brand.update_priority(brand_obj)
		#if brand_obj.priority_changed?
			all_brands = Brand.all
			lesser_priority = all_brands.collect{|t| t if t.priority < brand_obj.priority}.reject{|t| t.nil?}
			same_priority = all_brands.collect{|t| t if t.priority == brand_obj.priority}.reject{|t| t.nil?}
			bigger_priority = all_brands.collect{|t| t if t.priority > brand_obj.priority}.reject{|t| t.nil?}
			same_priority.each_with_index do |obj,index|
				if obj.id != brand_obj.id
					obj.update_attributes(priority: lesser_priority.size + 2)
				end
			end
			default_val = lesser_priority.size + 2 
			bigger_priority.each_with_index do |obj,index|
				obj.update_attributes(priority:  default_val + 1)
				default_val = default_val + 1
			end


			# all_brands.each_with_index do |brand,index|
			# 	if brand.priority < brand_obj.priority
			# 	elsif brand.priority == brand_obj.priority && brand.id != brand_obj.id
			# 		brand.update_attributes(priority: brand.priority + 1)
			# 	elsif brand.priority > brand_obj.priority
			# 		brand.update_attributes(priority: brand.priority + 1)
			# 	end
			# end
		#end
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all.order("priority ASC")
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    case params[:alias_name]
    when "phones"
      @phones = Phone.all.order("brand_id ASC")
      render :template => 'phones/index'
    when "phone_details"
      @phone_details = PhoneDetail.all.order("brand_id ASC")
      render :template => 'phone_details/index'
    when "blog"
      render :template => 'articles/index'
    else
      @brand = Brand.find_by(alias_name: params[:alias_name])
      @phones = @brand.phones.order("release_date DESC")
      @latest_releases = @phones.order("release_date ASC").limit(4)
    end
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit

  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)
    @brand.alias_name = @brand.name
    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    params[:brand][:alias_name] = params[:brand][:name]
    respond_to do |format|
      if @brand.update(brand_params)
        Brand.update_priority(@brand)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find_by(alias_name: params[:alias_name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.fetch(:brand).permit(:image,:logo,:name,:description,:alias_name,:priority)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%#= @brand.inspect %>
<%= simple_form_for(@brand,class: "form-horizontal") do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :name,input_html: {class: "form-control"}  %>
  </div>
  <!-- <div class="form-group">
    <%#= f.input :alias_name,input_html: {class: "form-control"}  %>
  </div> -->
  <div class="form-group">
    <%= f.input :description,input_html: {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.input :priority,input_html: {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.input :image, as: :file %>
  </div>
  <div class="form-group">
    <%= f.input :logo, as: :file %>
  </div>
  <div class="actions">
    <%= f.button :submit,"Submit",class: "btn btn-default" %>
  </div>
<% end %><br/>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Top Mobile Brands</h1>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>Priority</th>
      <th>Name</th>
      <td>Logo</td>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.priority  %></td>
        <td><b><%= link_to brand.name,brand %></b><%= brand.phones.length > 0 ? " (" + brand.phones.length.to_s + " Phones" + ")" : " (No phones available)" rescue nil%></td>
        <td><%= image_tag(brand.logo.url(:thumb))  %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit',edit_brand_path(brand.alias_name) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<div class="container">
	<div class="row"> 
		<div class="col-md-12" style="height:60px;vertical-align:center;margin-top:20px;">
			<ul class="list-inline">
				<li>
					<span style="float:left;clear:both;font-weight: bold;"><h2><%= @brand.name.upcase %></h2></span>
				</li>
				<li>
					<span style="float:left;"><h3><%= "(" + @phones.length.to_s + " Phones)"  %></h3></span>
				</li>
			</ul>

			<!-- <div style="float:left;clear:both;font-weight: bold;margin-top:0px;"><h2><%= @brand.name.upcase %></h2></div>
			<div style="float:left;"><h3><%= "( " + @phones.length.to_s + " Phones )"  %></h3></div> -->
    </div>
		<div class="col-md-10">
	    <% @phones.each do |phone| %>
				<div class="col-md-3 " style="margin-top:30px;">
					<a href="<%= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>">
						<!-- <div class="thumbnail">  -->
							<div class="p_image1">
								<%= phone.image.present? ? (image_tag(phone.image.url,class: "img-responsive",style: "height: 160px;height: 160px;display: block;margin: auto;width: auto;")) : image_tag("default.jpg",style: "height: 160px; width: 100%; display: block;") rescue nil%>
							</div>
							<div class="p_name_tag">
								<strong><%= phone.name.camelcase %></strong><br/><br/>
								<strong>Announced</strong><%= " " +  phone.phone_details.first.announced rescue nil %><br/>
								<strong>RAM</strong><%= " " + phone.phone_details.first.ram rescue nil %><br/>
								<strong>Internal</strong><%= " " + phone.phone_details.first.rom rescue nil %>
								
							</div>
						<!-- </div>  -->
					</a>
				</div> 
			<% end %> 
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div> 

app/views/brands/show1.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= @latest_releases.first.name %>
				<small><%= " (" + @brand.name + " latest release "  + ")"%></small>
			</h1>
		</div>
	</div>
	<div class="row">
		<a href="<%= '/phones/'+ @latest_releases.first.name.gsub(" ","_") rescue nil%>">
			<div class="col-md-8">
				<%=  File.exists?(Rails.root.to_s+"/app/assets/images/750*500/#{@brand.name.downcase}.jpg") ? image_tag("/assets/750*500/#{@brand.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "750x500") : image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500") rescue image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500")%>
			</div>
		</a>
		<div class="col-md-4">
			<h3>Description</h3>
			<p>
				<%= @brand.description.present? ? @brand.description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim." %>
			</p>
			<h3>Latest releases</h3>
			<ul>
				<% @latest_releases.each do |l_release| %>
					<li><%= l_release.name %></li>
				<% end %>
      </ul>
    </div>
  </div>
  <div class="row">
		<div class="col-lg-12">
    	<h3 class="page-header"><%= @brand.name + " Other Phones" %></h3>
    </div>
    <% @phones.each do |phone| %>
    	<div class="col-sm-3 col-xs-6">
    		<a href="<%= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>" style="text-align: center;">
    			<%=  File.exists?(Rails.root.to_s+"/app/assets/images/420*420/#{phone.name.downcase}.jpg") ? image_tag("/assets/420*420/#{phone.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "420x420") : image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420") rescue image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420")%>
					<h2><strong><span style="display: inline-table;text-align: center;width:100%;"><%= phone.name %></span></strong></h2><br/>
    		</a>
			</div>
    <% end %>
  </div>  
	<!-- Code by Milind -->
	<div class="row"> 
		<% @phones.each do |phone| %>
		<div class="col-sm-6 col-md-3" style="margin-top:30px;">
			<!-- <a href="<%#= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>"> -->
				<!-- <div class="thumbnail">  -->
					<div class="phone_image">
					<%= phone.image.present? ? (image_tag(phone.image.url,class: "img-responsive",style: "height: 212px;")) : image_tag("default.jpg",style: "height: 212px; width: 100%; display: block;") rescue nil%>
					</div>
					<div class="phone_name_tag">
						<strong><%= phone.name %></strong>
					</div>
				<!-- </div>  -->
			<!-- </a> -->
		</div> 
		<% end %> 
	</div>
</div> 

<!-- End of code -->